on:
  #push:
    #branches:
    #- dev
  workflow_dispatch:

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
    - name: checking out code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Reset dev branch
      run: |
        git fetch origin dev:dev
        git reset --hard dev

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "Requesting Pull Request"
        committer: Abdul <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        body: "I want to merge from feature branch to main"
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: true
        reviewers: "YAbdul" 
