on:
  push:
    branches:
    - main

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
    - name: checking out code
      uses: actions/checkout@v2

    - name: Raise pull-request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: "auto-pr-branch"
        base: main        
        title: "Requesting Pull Request"
        committer: Abdul <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        body: "I want to merge from feature branch to main"
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: true
        reviewers: "YAbdul" 